# Travis-CI Build for libgit2sharp
# see travis-ci.org for details

language: ruby

rvm:
 - ruby-head

os:
 - linux
 - osx

before_install:
 - date -u
 - uname -a
 - env | sort

# Make sure CMake and Mono are installed
install:
 - sudo apt-get install cmake mono-devel mono-gmcs

# Build libgit2, LibGit2Sharp and run the tests
script:
 - ./build.libgit2sharp.sh

# Only watch the development branch
branches:
 only:
   - vNext

# Notify development list when needed
notifications:
 email:
  recipients:
   - emeric.fermas@gmail.com
